all: assignment1wpi assignment1b

assignment1wpi: assignment1wpi.c
	gcc -I -Wall assignment1wpi.c -o assignment1wpi

assignment1b: assignment1b.c
	gcc -I -Wall assignment1b.c -o assignment1b
clean:
	rm assignment1wpi
	rm assignment1b
